env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - 2
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  no-unused-vars: 0
  no-console: 0
globals:
    describe: true
    it: true
    before: true
    after: true
    beforeEach: true
    afterEach: true
    __dirname: true