language: node_js
node_js:
  - 4.6.1
  - 6.9.1

before_deploy:
  - cd ./build

deploy:
  provider: heroku
  api_key:
    secure: Lm7WTEDqP9vMTQHpqRAvsRtkRYrWL5WdWu5qeQd7N+mJ8PA9e8F0bRVL2KYv6flWtC9pXkvtDbl4wtIpqta4uXJqa6kvjAo8TZc8U6WkRo9tVagmRtJ1jOF4N6FC6RmUCBPiwiFjUviUi0WTkND4YsK7bnK0OETmSMh3S6xZ0xGNve2CX3HTIZmSsROjSSPKd0+KS4Rsge2vYVErFOkp7Kd+RMY+kAUoJ5nzDBHpkTYY/QvZSMjevlLacOZM33tk9fNJhLic8KCI2nxFpOkYlpofurdxRQ26C8U1hCNx9Mya7Nr9OoQ33K+6U9kty4FQO0TQoTSS4mdTIe0O3GbbPCZk0RPnV2kGBN6zQbQDSB/JiIEIQ+XPGgywwq3SmGrvPrYsmTL07YBogZrV2SEJCW0/xLfLWWHIhir5s+4OesAY95lsNq07RUj+QIQFPJ037m2sAd9bAQvmOhGcY+ZH478yruE7nT/KQgRgyWSYiZ94CgpFNP6MYNAZOG2fRNoPbxyGXI8WURZDXfbEln6/k8nAP1akOtLIZy1EK1roXALzRIbCaWiCdsChR7nvsByZkHwUaX+CV2DEe2K4DdBJisfjj6Uw4niEEUhYsiHkG0Rz3Uce785cOzTgbESAiQCUaye8bP3uKQZTVNtNhT/W4DSJEfPDYGyA4foLRnT2p2M=
  app: moonhighway
  on:
    repo: eveporcello/moonhighway
    tags: true