language: node_js
node_js:
  - 4.6.1
  - 6.9.1

deploy:
  provider: heroku
  api_key:
    secure: ih+fNbeyvOML/pA5hpiA4VVMw6PoEIqRU0N9MoZxeKYeIqLp2PzzzO/QcJi90BksS9tJTWwe2M8fiCDJsgDjJ7mzMMLo0aGR7vf/xBqOBjIvSkAQJi+0NAy4alXQP2Bg6xp65RP6vOaJZ/NuZ0QeP1MdRB9wWsUY2wQd6puZHvoF3rEAYIvi2GTm1qoc0ozGmxofcNuXey2v/cFSikhRLiZizxiS1pkbfLtMFn40dvtSP93enBWH6vdr6zmJLaDHDffKd06xqrPM37cA/hbHWXBEJEj2TMApMuz+YvV1ZZBPLsmrWqFOV8nwRyF5lYt6nrPm0CcbSFIrAHIOOv1Q6EE4m/F3UDFEoXta3Ejdz3ijSkqDMk5bHZsRcpKuXkiaJHzyaDC0DWk5ZrhxYGRzoOcxG+2qvflKCUQnp/CxExNZAwlr/bWn/YsmuECZf2ZC+bpUpD9xiC8JQnd1YJZ1H/m2adWVkaIFA7kcuUv4ZQ/2y6dBXquEscjQohepQDRsjeA4xF53O91qOJK/Qi1OAZFGkurQvlafWeiywq3BMyuuJT6Jrv/peCYnBdgkZ9QluDGprgMk5zS/ySW2JFWuukuBl8tVVCMUyu/Ltv2xLW6b6gUg+RAwj7ZZzFZKq482F7LuNwSAnhDxwLFepiTMqyPRC5OAI47fjIfs1BWQGto=
  app: moonhighway
  on:
    repo: eveporcello/moonhighway
    branch: master    
